"""
Auto-generated from STAFF PAYROLL FOR APRIL 2026.xls -- CORRECTED.
Previous version read Cola column (10% of Gross) instead of Gross column.
Generated: 2026-02 by step3a_payroll_roster_v2 builder.
"""
# 217 employees across 19 outlets. Gross range: ₦39,820 – ₦3,391,719
PAYROLL_APR_2026_V2 = [
    {"outlet": 'Headquarters', "name": 'ABANIKANDA FEMI', "position": 'Operations Manager', "gross": 705600.0},
    {"outlet": 'Headquarters', "name": 'AYO AKINBOBOLA', "position": 'COO', "gross": 1747200.0},
    {"outlet": 'Headquarters', "name": 'JIMOH IBRAHIM', "position": 'Head Technical unit', "gross": 201110.0},
    {"outlet": 'Headquarters', "name": 'OGUNSHOLA NURUDEEN', "position": 'Depot rep.', "gross": 155610.0},
    {"outlet": 'Headquarters', "name": 'ISEME GLORY', "position": 'Secretary', "gross": 104104.0},
    {"outlet": 'Headquarters', "name": 'HANNAH DAVID EFFIONG', "position": 'Cleaner', "gross": 73941.0},
    {"outlet": 'Headquarters', "name": 'EWONA CHARITY', "position": 'Customer Care Rep', "gross": 118300.0},
    {"outlet": 'Headquarters', "name": 'OBI RASHEED', "position": 'Accountant', "gross": 371280.0},
    {"outlet": 'Headquarters', "name": 'OJERUSE ROLAND', "position": 'A.g Head of Sales & Marketing', "gross": 672000.0},
    {"outlet": 'Headquarters', "name": 'KILANKO ASHIMIYU', "position": 'Central Store Officer', "gross": 145600.0},
    {"outlet": 'Headquarters', "name": 'ADEBISI ADETUNJI', "position": 'Head, Human Resources & Admin', "gross": 622440.0},
    {"outlet": 'Headquarters', "name": 'ISMAIL ABOLORE DAVIES', "position": 'Finance Manager', "gross": 1286208.0},
    {"outlet": 'Headquarters', "name": 'RAZAQ ADIGUN', "position": 'Contact Centre supervisor', "gross": 273000.0},
    {"outlet": 'Headquarters', "name": 'OLUWAROTIMI BUKOLA', "position": 'Truck Driver', "gross": 155610.0},
    {"outlet": 'Headquarters', "name": 'ALAO ESTHER TITILAYO', "position": 'Account officer', "gross": 163100.0},
    {"outlet": 'Headquarters', "name": 'VICTORIA ESENAM ATIYOE', "position": 'Account officer', "gross": 163100.0},
    {"outlet": 'Headquarters', "name": 'ADEWUSI JIMOH ADIO', "position": 'Truck Driver', "gross": 155610.0},
    {"outlet": 'Headquarters', "name": 'JAMES AREMU OLADEJO', "position": 'Truck Driver', "gross": 155610.0},
    {"outlet": 'Headquarters', "name": 'OYEDELE ALIU BABATUNDE', "position": 'Bobtail truck', "gross": 117600.0},
    {"outlet": 'Headquarters', "name": 'FALANA OLUWATOYIN', "position": 'Commercial Sales Executive', "gross": 163100.0},
    {"outlet": 'Headquarters', "name": 'BANJO ADEDAYO', "position": 'Sales Executive', "gross": 280000.0},
    {"outlet": 'Headquarters', "name": 'ORIOYE TITUS SUNDAY', "position": 'Truck Driver', "gross": 155610.0},
    {"outlet": 'Headquarters', "name": 'OSHOALA KOREDE HAZEEM', "position": 'Operations assistant', "gross": 280000.0},
    {"outlet": 'Headquarters', "name": 'PROSPER OGALA', "position": 'Bulk Sale fulfilment', "gross": 118300.0},
    {"outlet": 'Headquarters', "name": 'OGUNREMI KEHINDE A.', "position": 'Bobtail truck', "gross": 117600.0},
    {"outlet": 'Headquarters', "name": 'OCHONOGOR OLISE', "position": 'Depot rep.', "gross": 155610.0},
    {"outlet": 'Headquarters', "name": 'AYODELE SHERIFDEEN', "position": 'Technician', "gross": 104104.0},
    {"outlet": 'Headquarters', "name": 'CHRISTIAN-DAN SUSAN', "position": 'Customer Care Rep', "gross": 118300.0},
    {"outlet": 'Headquarters', "name": 'AZEEZ SULAIMON ADEKUNLE', "position": 'Truck Driver', "gross": 155610.0},
    {"outlet": 'Headquarters', "name": 'OGUNTUASE MOSES TAYO', "position": 'Stock officer (accessories)', "gross": 223000.0},
    {"outlet": 'Headquarters', "name": 'AYINLA SIKIRU OLALEKAN', "position": 'Truck Driver', "gross": 155610.0},
    {"outlet": 'Headquarters', "name": 'ADEBAKIN SULAIMON', "position": 'Technician', "gross": 131540.0},
    {"outlet": 'Headquarters', "name": 'SALAU MUTIU', "position": 'Bobtail truck', "gross": 117600.0},
    {"outlet": 'Headquarters', "name": 'ADEWOYE ADESANYA', "position": 'Bobtail truck', "gross": 117600.0},
    {"outlet": 'Headquarters', "name": 'UBOJU PRINCE EMMANUEL', "position": 'Bobtail truck', "gross": 117600.0},
    {"outlet": 'Headquarters', "name": 'ADEBAYO DOLAPO DEBORAH', "position": 'Account Receivable', "gross": 180000.0},
    {"outlet": 'Headquarters', "name": 'OLUFUWAPE REUBEN', "position": 'Operations support', "gross": 223000.0},
    {"outlet": 'Headquarters', "name": 'Pension payable for the Month', "position": '1668795.534', "gross": 3391719.966},
    {"outlet": 'Ikeja', "name": 'OGBOJI SUNNY', "position": 'Technician', "gross": 141960.0},
    {"outlet": 'Ikeja', "name": 'AMEH MONDAY', "position": 'Plant Manager', "gross": 252000.0},
    {"outlet": 'Ikeja', "name": 'ABIODUN JACKSON', "position": 'Driver', "gross": 131040.0},
    {"outlet": 'Ikeja', "name": 'ADETANSOLA GABRIEL', "position": 'Fulfilment officer', "gross": 134316.0},
    {"outlet": 'Ikeja', "name": 'OKPAKO STELLA', "position": 'Plant supervisor (itele)', "gross": 196560.0},
    {"outlet": 'Ikeja', "name": 'NNAMANI JAMES AMAECHI', "position": 'Technician', "gross": 118300.0},
    {"outlet": 'Ikeja', "name": 'AUDU ABU', "position": 'Dispatch rider', "gross": 109200.0},
    {"outlet": 'Ikeja', "name": 'ANTHONY AMEH', "position": 'Driver', "gross": 131040.0},
    {"outlet": 'Ikeja', "name": 'OGUMAR SONIA', "position": 'commercial Rep', "gross": 116500.0},
    {"outlet": 'Ikeja', "name": 'ANYEBE OCHANYA ELIZABETH', "position": 'FUlfilment officer', "gross": 118300.0},
    {"outlet": 'Ikeja', "name": 'LAWAL MOHAMMED', "position": 'Platform supervisor', "gross": 134316.0},
    {"outlet": 'Ikeja', "name": 'SAMUEL DAVID AKPA', "position": 'Filler', "gross": 78078.0},
    {"outlet": 'Ikeja', "name": 'SULEIMAN ISMAIL', "position": 'Filler', "gross": 78078.0},
    {"outlet": 'Ikeja', "name": 'EFFIONG UKEME PEACE', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Ikeja', "name": 'AGADA EMMANUEL ELEOJO', "position": 'Filler', "gross": 91091.0},
    {"outlet": 'Ikeja', "name": 'VIHIMGA COURAGE T', "position": 'TRICYCLE RIDER', "gross": 109200.0},
    {"outlet": 'Ikeja', "name": 'EDORUME JONATHAN OBOAPOROHO', "position": 'Driver (Commercial)', "gross": 131040.0},
    {"outlet": 'Ikeja', "name": 'AGADA QUEEN ESTHER', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Ikeja', "name": 'GABRIEL EMMANUEL ADAH', "position": 'FILLER', "gross": 78078.0},
    {"outlet": 'Ikeja', "name": 'OKEWU QUEEN OJONUMA', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Ikeja', "name": 'SAHEED EGAJI USMAN', "position": 'RIDER', "gross": 109200.0},
    {"outlet": 'Ikeja', "name": 'AUDU MONDAY', "position": 'FILLER 2', "gross": 100800.0},
    {"outlet": 'Ikeja', "name": 'DURU JEREMIAH', "position": 'FILLER', "gross": 78078.0},
    {"outlet": 'Ikeja', "name": 'STEPHEN DENNIS OSEWE', "position": 'FILLER', "gross": 78078.0},
    {"outlet": 'Pedro', "name": 'ADEYEMI TAIWO NAFIU', "position": 'Filler', "gross": 78078.0},
    {"outlet": 'Pedro', "name": 'MATHEW CECILIA OLUWAKEMI', "position": 'Plant supervisor', "gross": 196560.0},
    {"outlet": 'Pedro', "name": 'DUFF EFFIONG', "position": 'Platform supervisor', "gross": 118300.0},
    {"outlet": 'Pedro', "name": 'AYODELE BOLANLE ROFIAT', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Pedro', "name": 'ABILAWON BOLAJOKO', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Pedro', "name": 'SALAU ADEDOLAPO IBRAHIM', "position": 'Filler', "gross": 78078.0},
    {"outlet": 'Oshodi', "name": 'UDOH JOHN', "position": 'Platform supervisor', "gross": 196560.0},
    {"outlet": 'Oshodi', "name": 'BISHOP AMOS', "position": 'rider', "gross": 109200.0},
    {"outlet": 'Oshodi', "name": 'HASSAN ADESEYE OMOJOLA', "position": 'Filler', "gross": 78078.0},
    {"outlet": 'Oshodi', "name": 'JOSEPH ADAMA', "position": 'RIDER', "gross": 109200.0},
    {"outlet": 'Oshodi', "name": 'NEGEDU CALEB ENYO-OJO', "position": 'Filler', "gross": 78078.0},
    {"outlet": 'Oshodi', "name": 'AKOGWU BLESSING', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Oshodi', "name": 'MOSES RACHEAL REMILEKUN', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Oshodi', "name": 'AGABIELESIN EMMANUEL OPEYEMI', "position": 'Filler', "gross": 78078.0},
    {"outlet": 'Oshodi', "name": 'VICTOR ENEOJO JOHN', "position": 'Filler', "gross": 78078.0},
    {"outlet": 'Aseese', "name": 'ADEWALE ADENIYI', "position": 'SUPERVISOR', "gross": 196560.0},
    {"outlet": 'Aseese', "name": 'MORGAN FRIDAY', "position": 'PLATFORM SUPERVISOR', "gross": 118300.0},
    {"outlet": 'Aseese', "name": 'BAKARE OLUWAFUNKE MORENIKE', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Aseese', "name": 'AMOS BLESSING CHIAMAKA', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Aseese', "name": 'LAWAL TOYIN', "position": 'Cleaner', "gross": 65211.71},
    {"outlet": 'Aseese', "name": 'TOSIN KAYODE EMMANUEL', "position": 'Tricycle rider', "gross": 100800.0},
    {"outlet": 'Aseese', "name": 'HAMMED TAOHEED', "position": 'Filler', "gross": 78078.0},
    {"outlet": 'Aseese', "name": 'KUFORIJI BAZEET OLAMILEKAN', "position": 'Filler', "gross": 78078.0},
    {"outlet": 'Iju-Otta', "name": 'HASSAN TAIWO LATEEFAT', "position": 'Plant Supervisor', "gross": 196560.0},
    {"outlet": 'Iju-Otta', "name": 'IBIWOYE OMOWUNMI ADURAGBEMI', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Iju-Otta', "name": 'AGBEDEYI ABIGEAL', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Iju-Otta', "name": 'SHODEINDE LUKMON ORIYOMI', "position": 'FILLER', "gross": 91091.0},
    {"outlet": 'Iju-Otta', "name": 'OSHO MAYOKUN JOHN', "position": 'Filler', "gross": 78078.0},
    {"outlet": 'Iju-Otta', "name": 'ADEOYE ADEKUNLE', "position": 'FILLER', "gross": 78078.0},
    {"outlet": 'Iju-Otta', "name": 'KAREEM KAOSARA ENIOLA', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Iju-Otta', "name": 'ABIOLA ADEPOJU', "position": 'CLEANER', "gross": 46126.53},
    {"outlet": 'Iju-Otta', "name": 'ABIONA ROTIMI DANIEL', "position": 'FILLER', "gross": 78078.0},
    {"outlet": 'Osi-Otta', "name": 'PATRICK SUCCESS', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Osi-Otta', "name": 'AKINWALERE FUNMILAYO', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Osi-Otta', "name": 'OGUGUOM EUNICE', "position": 'Cleaner', "gross": 46126.53},
    {"outlet": 'Osi-Otta', "name": 'KOREDE AYOMIDE', "position": 'PlaNT Supervisor', "gross": 163100.0},
    {"outlet": 'Osi-Otta', "name": 'ARIYO OLAOLUWA OLANREWAJU', "position": 'Filler', "gross": 78078.0},
    {"outlet": 'Osi-Otta', "name": 'EDE SAMUEL', "position": 'TRICYCLE RIDER', "gross": 100800.0},
    {"outlet": 'Sefu', "name": 'ADEOYE ADEWALE', "position": 'PLANT MANAGER', "gross": 252000.0},
    {"outlet": 'Sefu', "name": 'ADEDEJI WURAOLA GRACE', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Sefu', "name": 'ADEWALE ESTHER', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Sefu', "name": 'ADARALEGBE BUKOLA', "position": 'CLEANER', "gross": 56215.75},
    {"outlet": 'Sefu', "name": 'CHIGOZIE EBONUGWO STEPHEN', "position": 'FILLER', "gross": 78078.0},
    {"outlet": 'Sefu', "name": 'AMAEFULE VALENTINE', "position": 'PLATFORM SUPERVISOR', "gross": 118300.0},
    {"outlet": 'Maba', "name": 'OLAIYA KAFAYAT', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Maba', "name": 'AKOMOLAFE AYODEJI FEMI', "position": 'PLATFORM SUP', "gross": 118300.0},
    {"outlet": 'Maba', "name": 'OGUNKANLU ABOLADE EZEKIEL', "position": 'filler', "gross": 91091.0},
    {"outlet": 'Maba', "name": 'KADEJO MARY', "position": 'CLEANER', "gross": 46126.53},
    {"outlet": 'Maba', "name": 'ADESINA OLUWASETEMI D.', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Maba', "name": 'HAMMED WALIU ALADE', "position": 'FILLER', "gross": 78078.0},
    {"outlet": 'Maba', "name": 'AMBALI OLAWALE', "position": 'PLANT SUP', "gross": 196560.0},
    {"outlet": 'Ijoko', "name": 'TEMILOLA OLUGBENGA O.', "position": 'Plant supervisor Ijoko', "gross": 163100.0},
    {"outlet": 'Ijoko', "name": 'OLAWOLE OLUWASEYI', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Ijoko', "name": 'OLUWASEGUN OMOLADE MARY', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Ijoko', "name": 'AKINLADE AYOMIDE MICHAEL', "position": 'FILLER', "gross": 60870.78},
    {"outlet": 'Ijoko', "name": 'KILASHO FATAI', "position": 'PLATFORM SUPERVISOR', "gross": 91091.0},
    {"outlet": 'Ijoko', "name": 'ADEWUNMI AKINYEMI', "position": 'RIDER', "gross": 78078.0},
    {"outlet": 'Ebute', "name": 'OLAWOYIN OLADAYO', "position": 'Plant supervisor Ijoko', "gross": 196560.0},
    {"outlet": 'Ebute', "name": 'ADEKOYA TOSIN SEYIFUNMI', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Ebute', "name": 'SHONUBI OLUWUNMI AFOLAKE', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Ebute', "name": 'KAREEM EMMANUEL', "position": 'FILLER', "gross": 78078.0},
    {"outlet": 'Ebute', "name": 'AYINLA SUNDAY BOLUWATIFE', "position": 'FILLER', "gross": 78078.0},
    {"outlet": 'Ebute', "name": 'KUDIRAT TITILAYO MURITADOR', "position": 'CLEANER', "gross": 46126.53},
    {"outlet": 'Upper Mission', "name": 'AHMED YAKUBU', "position": 'Technician (contract staff)', "gross": 94640.0},
    {"outlet": 'Upper Mission', "name": 'EKI ATAIGIE', "position": 'Cleaner', "gross": 39820.77},
    {"outlet": 'Upper Mission', "name": 'ONUWABHAGBE JOHN', "position": 'Driver', "gross": 105287.0},
    {"outlet": 'Upper Mission', "name": 'BENJAMIN ENOBOH', "position": 'Bobtail driver', "gross": 117600.0},
    {"outlet": 'Upper Mission', "name": 'MICHAEL VICTORIA', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Upper Mission', "name": 'HAWA YAKUBU', "position": 'A.g Plant Manager', "gross": 196560.0},
    {"outlet": 'Upper Mission', "name": 'AYEGHER TERHEMBA', "position": 'Rider', "gross": 105287.0},
    {"outlet": 'Upper Mission', "name": 'IGBUDU MSUGHTER BARTHOLOMEW', "position": 'PLATFORM SUP', "gross": 118300.0},
    {"outlet": 'Upper Mission', "name": 'PIUS SARAH ANGEL', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Upper Mission', "name": 'OLADIMEJI BUKOLA MARY', "position": 'Fulfilment officer', "gross": 118300.0},
    {"outlet": 'Upper Mission', "name": 'EZE IGNATIUS', "position": 'filler', "gross": 78078.0},
    {"outlet": 'Upper Mission', "name": 'OSAGIE VICTOR IMONITIE', "position": 'filler', "gross": 78078.0},
    {"outlet": 'Upper Mission', "name": 'OGBEVOEN WISDOM', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Upper Mission', "name": 'IRENE EMMANUEL', "position": 'filler', "gross": 78078.0},
    {"outlet": 'Upper Mission', "name": 'SULAIMAN NIMOTA AYOBAMI', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Upper Mission', "name": 'OKPARA CHUKWUEMEKA', "position": 'FILLER', "gross": 78078.0},
    {"outlet": 'Upper Mission', "name": 'OKOTOGBO GIFT', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Upper Mission', "name": 'AYO SUNDAY ILESANMI', "position": 'Rider', "gross": 105287.0},
    {"outlet": 'Upper Mission', "name": 'SAMUEL ANTHONY', "position": 'Rider', "gross": 105287.0},
    {"outlet": 'Upper Mission', "name": 'IGBINOBA VICTOR', "position": 'FILLER', "gross": 78078.0},
    {"outlet": 'Upper Mission', "name": 'JOHN DOMION', "position": 'filler', "gross": 78078.0},
    {"outlet": 'Upper Mission', "name": 'UGWOKE OBINNA PRINCEWELL', "position": 'filler', "gross": 78078.0},
    {"outlet": 'Idokpa', "name": 'UWAGWE MACAULEY', "position": 'PLANT MANAGER', "gross": 252000.0},
    {"outlet": 'Idokpa', "name": 'OYIZA DEBORAH', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Idokpa', "name": 'IFY CHUKS', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Idokpa', "name": 'AFENGBAI TIMOTHY', "position": 'FILLER', "gross": 78078.0},
    {"outlet": 'Idokpa', "name": 'SHITTU BABATUNDE', "position": 'FILLER', "gross": 78078.0},
    {"outlet": 'Idokpa', "name": 'CHINELO ANIEGBUANAM', "position": 'CLEANER', "gross": 46500.0},
    {"outlet": 'Idokpa', "name": 'MOMODU RASHEED', "position": 'FILLER', "gross": 78078.0},
    {"outlet": 'Ekehuan', "name": 'ALOZIE FAITH', "position": 'Plant Manager', "gross": 252000.0},
    {"outlet": 'Ekehuan', "name": 'DENEDO JEREMIAH', "position": 'Filler I', "gross": 91091.0},
    {"outlet": 'Ekehuan', "name": 'IORPUU EMMANUEL', "position": 'Platform Supervisor', "gross": 134316.0},
    {"outlet": 'Ekehuan', "name": 'OSADOLOR OSAMWONYI', "position": 'Rider', "gross": 105287.0},
    {"outlet": 'Ekehuan', "name": 'OBAZU JEREMIAH', "position": 'Technician (Benin)', "gross": 134316.0},
    {"outlet": 'Ekehuan', "name": 'SHIMA JUSTINE AONDOAKULA', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Ekehuan', "name": 'ORTSERGA SAMUEL', "position": 'Filler', "gross": 78078.0},
    {"outlet": 'Ekehuan', "name": 'IGBINEDE EMMANUEL', "position": 'Bobtail rep', "gross": 105287.0},
    {"outlet": 'Ekehuan', "name": 'ODIHI GIFT', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Ekehuan', "name": 'EMMANUEL ANANDE', "position": 'Rider', "gross": 105287.0},
    {"outlet": 'Ekehuan', "name": 'OKUWHERE HELEN', "position": 'CLEANER', "gross": 56215.75},
    {"outlet": 'Ekehuan', "name": 'USHAHEMBA AYEM VICTOR', "position": 'FILLER', "gross": 78078.0},
    {"outlet": 'Ekehuan', "name": 'MELODY UDJOR OGHENEVWEGBA', "position": 'FILLER', "gross": 78078.0},
    {"outlet": 'Ekehuan', "name": 'FAVOUR OGOCHUKWU', "position": 'FILLER', "gross": 78078.0},
    {"outlet": 'Okhuoromi', "name": 'OBI VICTOR', "position": 'A.g Plant Manager', "gross": 196560.0},
    {"outlet": 'Okhuoromi', "name": 'TAKPOR EFE', "position": 'Platform Supervisor', "gross": 134316.0},
    {"outlet": 'Okhuoromi', "name": 'EMMANUELLA BENJAMIN', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Okhuoromi', "name": 'DOMINION ROLAND', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Okhuoromi', "name": 'BULUS SATI', "position": 'RIDER', "gross": 105287.0},
    {"outlet": 'Okhuoromi', "name": 'GODWIN SAVIOUR', "position": 'RIDER', "gross": 105287.0},
    {"outlet": 'Okhuoromi', "name": 'ISAAC ONWUZULUIGBO', "position": 'FILLER', "gross": 78078.0},
    {"outlet": 'Idowina', "name": 'AYOMIDE JOSHUA', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Idowina', "name": 'EKHOWMANYE RUTH', "position": 'Cashier/fulfiment', "gross": 99372.0},
    {"outlet": 'Idowina', "name": 'ORIAKHI RACHEAL O.', "position": 'Plant Manager', "gross": 252000.0},
    {"outlet": 'Idowina', "name": 'DANIEL DAVID', "position": 'FILLER', "gross": 78078.0},
    {"outlet": 'Idowina', "name": 'SATURDAY ALETOR EFFOR', "position": 'RIDER', "gross": 105287.0},
    {"outlet": 'Idowina', "name": 'BLESSING NGAWCHI', "position": 'CLEANER', "gross": 46500.0},
    {"outlet": 'Asaba', "name": 'IYARE FAVOUR', "position": 'PLANT SUPERVISOR', "gross": 196560.0},
    {"outlet": 'Asaba', "name": 'EMADU BLESSING', "position": 'PLATFORM SUPERVISOR', "gross": 167985.0},
    {"outlet": 'Asaba', "name": 'OKON ENDURANCE', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Asaba', "name": 'MMADUABUCHI CHIKODI', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Asaba', "name": 'STANLEY IDRIS', "position": 'FILLER', "gross": 91091.0},
    {"outlet": 'Asaba', "name": 'ANAS SHAMSUDDEEN', "position": 'FILLER', "gross": 91091.0},
    {"outlet": 'Asaba', "name": 'ONOMEASIKELE GODWIN O.', "position": 'FILLER', "gross": 91091.0},
    {"outlet": 'Reclamation', "name": 'ABIGAIL SOLOMON', "position": 'Plant Manager', "gross": 252000.0},
    {"outlet": 'Reclamation', "name": 'DANIEL ALABO DOKUBO', "position": 'Platform supervisor', "gross": 118300.0},
    {"outlet": 'Reclamation', "name": 'FRIDAY PRAISE', "position": 'Driver', "gross": 131040.0},
    {"outlet": 'Reclamation', "name": 'NWANKWO EMMANUEL NICHOLAS', "position": 'Filler', "gross": 78078.0},
    {"outlet": 'Reclamation', "name": 'GODKNOWS SOLOMON', "position": 'Filler', "gross": 91091.0},
    {"outlet": 'Reclamation', "name": 'HENRY JOHNSON YOWIKA', "position": 'FILLER', "gross": 78078.0},
    {"outlet": 'Reclamation', "name": 'KALADA VICTOR GREEN', "position": 'Fulfilment officer', "gross": 118300.0},
    {"outlet": 'Reclamation', "name": 'COVENANT EFFIONG', "position": 'filler', "gross": 78078.0},
    {"outlet": 'Reclamation', "name": 'NNOROM EMMANUEL', "position": 'cashier', "gross": 99372.0},
    {"outlet": 'Reclamation', "name": 'VINCENT JONNY UWEN', "position": 'Filler', "gross": 78078.0},
    {"outlet": 'Reclamation', "name": 'SAMUEL NANIA MICHAEL', "position": 'Filler', "gross": 78078.0},
    {"outlet": 'Reclamation', "name": 'AGBEGE OSEMUDIAMEN FELICITY', "position": 'cashier', "gross": 99372.0},
    {"outlet": 'Reclamation', "name": 'SARAH WEALTH', "position": 'CLEANER', "gross": 56215.75},
    {"outlet": 'Reclamation', "name": 'WISDOM SUNEBARI NAADE', "position": 'Filler', "gross": 78078.0},
    {"outlet": 'Reclamation', "name": 'AKARI OTUOTU', "position": 'Driver', "gross": 105287.0},
    {"outlet": 'Reclamation', "name": 'EBIKONBOERE FLOURISH AKUNA', "position": 'cashier', "gross": 99372.0},
    {"outlet": 'Reclamation', "name": 'HONESTY SAMUEL', "position": 'Filler', "gross": 78078.0},
    {"outlet": 'Reclamation', "name": 'OSINACHI NWAOBA', "position": 'Filler', "gross": 78078.0},
    {"outlet": 'Reclamation', "name": 'GODSPOWER FIRST SOLOMON', "position": 'Filler', "gross": 78078.0},
    {"outlet": 'Reclamation', "name": 'PAUL DOMINIC JAMES', "position": 'TRICYCLE RIDER', "gross": 105287.0},
    {"outlet": 'Eleme', "name": 'FIDELIS AKPAN GODWIN', "position": 'Plant Manager', "gross": 252000.0},
    {"outlet": 'Eleme', "name": 'NWOBODO IZUCHUKWU E.', "position": 'Platform supervisor', "gross": 167985.0},
    {"outlet": 'Eleme', "name": 'ENUGU WISDOM', "position": 'Filler', "gross": 91091.0},
    {"outlet": 'Eleme', "name": 'BARIYAA JOHN TAMBARI', "position": 'Driver', "gross": 105287.0},
    {"outlet": 'Eleme', "name": 'ELTON GABRIEL', "position": 'filler', "gross": 91091.0},
    {"outlet": 'Eleme', "name": 'NNANNA HUMBLE AMARACHI', "position": 'Cleaner', "gross": 56215.75},
    {"outlet": 'Eleme', "name": 'ECHEAZU CHIDIMMA PATIENCE', "position": 'Cashier', "gross": 99372.0},
    {"outlet": 'Eleme', "name": 'AKARI ILAMI THANKGOD', "position": 'Cashier/Fulfilment', "gross": 99372.0},
    {"outlet": 'Eleme', "name": 'ABIGAIL NANEE', "position": 'CASHIER', "gross": 99372.0},
]
