"""
Phase 5.7 / Step 4: POS Closing Entry pre-check.

When a cashier tries to close their shift, this check (called from POS
Closing Entry's `validate` hook OR run manually) blocks closure if any
of the cashier's invoices for this shift are still in Draft -- i.e., a
queued background-submit job hasn't finished yet.

Without this check, the cashier sees a 'Net Total' that excludes queued
invoices -> shortfall apparent at end of shift -> mistaken cash overage
or shortage reported.

Two run modes:
  1. CHECK_MODE='audit'  -- read-only, list any closing entries with
                            stale drafts. Run today to see if you have any.
  2. CHECK_MODE='enforce' -- patches POS Closing Entry to call the check
                             before saving. Requires submit_in_background
                             to have flushed within MAX_WAIT_SECONDS.

Run:
    SHA=<commit>
    curl -fsSL "https://raw.githubusercontent.com/sungasng/POS-Awesome-V15/$SHA/scripts/p57_step4_closing_precheck.py" -o /tmp/p57d.py
    bench --site sungasmis.v.frappe.cloud execute "exec(open('/tmp/p57d.py').read())"
"""

from __future__ import annotations
import frappe


CHECK_MODE       = "audit"      # 'audit' or 'enforce'
MAX_WAIT_SECONDS = 60           # used only in enforce mode


def find_closing_with_stale_drafts() -> list[dict]:
    """For each draft POS Closing Entry, count open Sales Invoices in its window."""
    rows = frappe.db.sql("""
        select pce.name as closing_name, pce.pos_profile, pce.user,
               pce.period_start_date, pce.period_end_date, pce.posting_date,
               count(si.name) as draft_inv_count,
               sum(si.grand_total) as draft_total
        from `tabPOS Closing Entry` pce
        left join `tabSales Invoice` si
          on si.pos_profile = pce.pos_profile
         and si.owner = pce.user
         and si.docstatus = 0
         and si.is_pos = 1
         and si.creation between pce.period_start_date and pce.period_end_date
        where pce.docstatus = 0
        group by pce.name
        having draft_inv_count > 0
        order by pce.modified desc
    """, as_dict=True)
    return rows


def install_validation_hook() -> None:
    """Create a Server Script of type DocType Event = 'Validate' on POS Closing Entry."""
    name = "POS Closing -- Block On Stale Drafts"
    code = f'''
# Auto-generated by p57_step4_closing_precheck.py
# Blocks POS Closing Entry save/submit if any of the user's invoices
# in the shift window are still Draft.

import frappe

stale = frappe.db.sql("""
    select name, grand_total, creation
    from `tabSales Invoice`
    where pos_profile = %(pp)s
      and owner = %(u)s
      and docstatus = 0
      and is_pos = 1
      and creation between %(s)s and %(e)s
""", {{"pp": doc.pos_profile, "u": doc.user, "s": doc.period_start_date, "e": doc.period_end_date}}, as_dict=True)

if stale:
    rows = "\\n".join(f"  - {{r['name']}} (NGN {{r['grand_total']:,.2f}}, {{r['creation']}})" for r in stale[:5])
    frappe.throw(
        f"Cannot close shift: {{len(stale)}} POS invoice(s) still in Draft.\\n\\n{{rows}}\\n\\n"
        f"Wait up to {MAX_WAIT_SECONDS}s for background submission to complete, "
        f"then retry. If still stuck, contact Accounts to triage."
    )
'''.strip()

    if frappe.db.exists("Server Script", name):
        ss = frappe.get_doc("Server Script", name)
        ss.script = code
        ss.disabled = 0
        ss.save(ignore_permissions=True)
    else:
        ss = frappe.get_doc({
            "doctype":        "Server Script",
            "name":           name,
            "script_type":    "DocType Event",
            "reference_doctype": "POS Closing Entry",
            "doctype_event":  "Validate",
            "script":         code,
        })
        ss.flags.ignore_permissions = True
        ss.insert()
    frappe.db.commit()
    print(f"  + Installed Server Script: {name!r}")


def main() -> None:
    print("=" * 72)
    print(f" Phase 5.7 / Step 4 -- POS Closing Entry pre-check  (mode={CHECK_MODE})")
    print("=" * 72)
    print()

    if CHECK_MODE == "audit":
        rows = find_closing_with_stale_drafts()
        if not rows:
            print("  Healthy: no draft Closing Entries have stale Draft invoices.")
            return
        print(f"  Found {len(rows)} draft Closing Entries with stale Draft invoices:")
        for r in rows:
            print(f"  - {r['closing_name']} (user={r['user']}, profile={r['pos_profile']}):")
            print(f"      window {r['period_start_date']} -> {r['period_end_date']}")
            print(f"      {r['draft_inv_count']} draft invoices totalling NGN {r['draft_total']:,.2f}")
        print()
        print("  Recommendation: set CHECK_MODE='enforce' to install the validation hook.")

    elif CHECK_MODE == "enforce":
        install_validation_hook()
        print()
        print("  POS Closing Entry will now reject save if any of the cashier's invoices")
        print("  for the shift window are still Draft. Cashier sees a clear error and")
        print("  knows to wait for background submission to flush.")

    else:
        print(f"  ! Unknown CHECK_MODE: {CHECK_MODE!r}. Use 'audit' or 'enforce'.")


try:
    _g = globals()
    for _k, _v in list(locals().items()):
        if _k not in _g:
            _g[_k] = _v
except Exception:
    pass

main()
